version: '3' # docker compose version

services:
  nginx: # nginx container
    image: nginx:inception
    container_name: nginx
    pull_policy: never
    build:
      context: ./requirements/nginx/ # Dockerfile folder
      dockerfile: Dockerfile
    ports:
      - "443:443" # host 443 port로 연결
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      inception-network:
        aliases: 
          - ${DOMAIN_NAME}
    restart: always
    env_file: .env
    depends_on:
      wordpress:
        condition: service_healthy


  wordpress:
    image: wordpress:inception
    container_name: wordpress
    pull_policy: never
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - inception-network
    restart: always
    env_file: .env
    depends_on:
      mariadb:
        condition: service_healthy
    healthcheck:
      test: ["CMD-SHELL", "wp core is-installed --allow-root || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

  mariadb:
    image: mariadb:inception
    container_name: mariadb
    pull_policy: never
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    expose:
      - "3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - inception-network
    restart: always
    env_file: .env
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -hlocalhost -udham -p${MYSQL_PASSWORD} || exit 1"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s

networks:
  inception-network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /Users/${USER}/docker-data/wordpress # mac
      device: /home/${USER}/data/wordpress # linux
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      # device: /Users/${USER}/docker-data/mariadb # mac
      device: /home/${USER}/data/mariadb # linux
