version: '3' # docker compose version

services:
  nginx: # nginx container
    build:
      context: ./requirements/nginx/ # Dockerfile folder
      dockerfile: Dockerfile
    ports:
      - "443:443" # host 443 port로 연결
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - nginx-wordpress-network
    restart: on-failure
    env_file: .env
    image: nginx
    container_name: nginx
    pull_policy: never

  wordpress:
    build:
      context: ./requirements/wordpress/
      dockerfile: Dockerfile
    expose:
      - "9000"
    volumes:
      - wordpress_volume:/var/www/html
    networks:
      - nginx-wordpress-network
      - wordpress-mariadb-network
    restart: on-failure
    env_file: .env
    image: wordpress
    container_name: wordpress
    pull_policy: never
    depends_on:
      - mariadb

  mariadb:
    build:
      context: ./requirements/mariadb/
      dockerfile: Dockerfile
    expose:
      - "3306"
    volumes:
      - mariadb_volume:/var/lib/mysql
    networks:
      - wordpress-mariadb-network
    restart: on-failure
    env_file: .env
    image: mariadb
    container_name: mariadb
    pull_policy: never

networks:
  nginx-wordpress-network:
    driver: bridge
  wordpress-mariadb-network:
    driver: bridge

volumes:
  wordpress_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/wordpress
  mariadb_volume:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/${USER}/data/mariadb