version: '3'

services:
  nginx:
    build:
      context: .
      dockerfile: ./nginx/Dockerfile
    ports:
      - "443:443"
    volumes:
      - /home/login/data/nginx:/etc/nginx
    networks:
      - nginx-wordpress-network

  wordpress-phpfpm:
    build:
      context: .
      dockerfile: ./wordpress/Dockerfile
    expose:
      - "9000"
    volumes:
      - /home/login/data/nginx:/var/www/html
    networks:
      - nginx-wordpress-network
      - wordpress-mariadb-network
    depends_on:
      - mariadb

  mariadb:
    build:
      context: .
      dockerfile: ./mariadb/Dockerfile
    expose:
      - "3306"
    volumes:
      - /home/login/data/mariadb:/var/lib/mysql
    networks:
      - wordpress-mariadb-network

networks:
  nginx-wordpress-network:
    driver: bridge
  wordpress-mariadb-network:
    driver: bridge
